packages:
  - apps/*

catalog:
  '@biomejs/biome': 2.2.0
  '@types/node': ^20
  '@types/react': ^19
  '@types/react-dom': ^19
  babel-plugin-react-compiler: 1.0.0
  next: 16.0.3
  react: 19.2.0
  react-dom: 19.2.0
  typescript: ^5

onlyBuiltDependencies:
  - sharp
